#!/bin/bash

source /usr/share/aurora/.funText

export COLOR_RESET="\e[0m"
export RED_B="\e[1;31m"
export GEEN_B="\e[1;32m"
export YELLOW_B="\e[1;33m"
export BLUE_B="\e[1;34m"
export MAGENTA_B="\e[1;35m"
export LIGHT_BLUE_B="\e[1;38;5;81m"
export PINK_B="\e[1;38;5;213m"
export PURPLE_B="\e[1;38;5;55m"
export CYAN_B="\e[1;38;5;36m"

export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
export PAGER=less
export TERM=xterm-256color

alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias grep='grep --color=auto'
alias reboot='reboot -f'

if [ "$UID" = "0" ]; then
    export PROMPT_COMMAND='PS1="\e[1;31m\u@\h \e[1;33m$(date +"%H:%M %b %d")\e[1;32m \w/\e[0m "'
else
    export PROMPT_COMMAND='PS1="\e[1;34m\u@\h \e[1;33m$(date +"%H:%M %b %d")\e[1;32m \w/\e[0m "'
fi

debug_run() {
    if $debug; then
        echo -n "run $@? (enter)"
        read
        $@
    else
        $@
    fi
}

debug_msg() {
  if $debug; then
    echo_c $@
  fi
}

get_largest_cros_blockdev() {
	local largest size dev_name tmp_size remo
	size=0
	for blockdev in /sys/block/*; do
		dev_name="${blockdev##*/}"
		echo -e "$dev_name" | grep -q '^\(loop\|ram\)' && continue
		tmp_size=$(cat "$blockdev"/size)
		remo=$(cat "$blockdev"/removable)
		if [ "$tmp_size" -gt "$size" ] && [ "${remo:-0}" -eq 0 ]; then
			case "$(sfdisk -d "/dev/$dev_name" 2>/dev/null)" in
				*'name="STATE"'*'name="KERN-A"'*'name="ROOT-A"'*)
					largest="/dev/$dev_name"
					size="$tmp_size"
					;;
			esac
		fi
	done
	echo -e "$largest"
}

get_partitions() {
    export cros_drive="$(get_largest_cros_blockdev)"
    export cros_stateful=$(cgpt find -l STATE ${cros_drive} 2>/dev/null | head -n 1 | grep --color=never /dev/)
    export cros_kern_a=$(cgpt find -l KERN-A ${cros_drive} 2>/dev/null | head -n 1 | grep --color=never /dev/)
    export cros_root_a=$(cgpt find -l ROOT-A ${cros_drive} 2>/dev/null | head -n 1 | grep --color=never /dev/)
    export cros_kern_b=$(cgpt find -l KERN-B ${cros_drive} 2>/dev/null | head -n 1 | grep --color=never /dev/)
    export cros_root_b=$(cgpt find -l ROOT-B ${cros_drive} 2>/dev/null | head -n 1 | grep --color=never /dev/)
}
get_partitions

declare -A VERSION
VERSION["BRANCH"]="alpine"
VERSION["NUMBER"]="shrimp"
VERSION["BUILDDATE"]="[2025-09-24]"
VERSION["RELNAME"]="Rhymes with Grug"
VERSION["STRING"]="v${VERSION["NUMBER"]} ${VERSION["BRANCH"]} - \"${VERSION["RELNAME"]}\""

canwifi() {
    update-ca-certificates 2>/dev/null
    ntpd -q -p pool.ntp.org 2>/dev/null
    ntpd -q -p pool.ntp.org 2>/dev/null
    if curl -Is https://example.com | head -n 1 | grep -q "HTTP/"; then
        "$@"
    else
        fail "Not connected to the internet"
    fi
}

echo_c() {
    local text="$1"
    local color_variable="$2"
    local color="${!color_variable}"
    echo -e "${color}${text}${COLOR_RESET}"
}

announcement() {
    if [ -n "$errormsg" ]; then
        echo -en "${RED_B}"
        echo "Error: ${errormsg}" | center
        echo -e "${COLOR_RESET}"
    elif [ -e "/etc/aurorannouncement" ]; then
        echo -en "${GEEN_B}"
        cat /etc/aurorannouncement 2>/dev/null | center
        echo -e "${COLOR_RESET}"
    fi
}

center() {
    local width=$(tput cols)
    local offset="${1:-0}"
    while IFS= read -r line || [[ -n $line ]]; do
		local plain=$(printf '%s' "$line" | tr -d '\0' | sed -E 's/\e\[[0-9;]*[mK]//g')
        local len=${#plain}
        local pad=$(( (width - len) / 2 + offset ))
        (( pad < 0 )) && pad=0
        printf "%*s%s\n" "$pad" "" "$line"
    done
}

read_center() {
    local dynamic=0
    if [[ "$1" == "-d" ]]; then
        dynamic=1
        shift
    fi

    local prompt="$1"
    local readvar="$2"
    local offset="${3:-0}"
    local width=$(tput cols)

    local plain=$(echo -e "$prompt" | sed -E 's/\e\[[0-9;]*[mK]//g')
    local plen=${#plain}
    local pad=$(( (width - plen) / 2 + offset ))
    (( pad < 0 )) && pad=0

    if (( ! dynamic )); then
        printf "%*s%s" "$pad" "" "$prompt"
        if [[ -n "$readvar" ]]; then
            read -r "$readvar"
        else
            read -r
        fi
    else
        printf "%*s%s" "$pad" "" "$prompt"

        local input=""
        local char=""
        local ilen=0
        local nowrap=1

        local stty=$(stty -g)
        stty -icanon -echo

        while IFS= read -rsn1 char; do
            if [[ -z $char ]]; then
                break
            elif [[ $char == $'\x7f' || $char == $'\x08' || $char == $'\b'  || $char == '^H' ]]; then
                if [[ -n $input ]]; then
                    input="${input::-1}"
                    ((ilen--))
                    tput cr
                    tput el
                    local pad=$(( (width - plen - ilen) / 2 + offset ))
                    (( pad < 0 )) && pad=0
                    printf "%*s%s%s" "$pad" "" "$prompt" "$input"
                fi
            elif [[ $char == $'\e' ]]; then
                read -rsn2 discard
                continue
            else
                input+="$char"
                ((ilen++))

                if (( nowrap && (plen + ilen >= width) )); then
                    nowrap=0
                    echo -n "$char"
                elif (( nowrap )); then
                    tput cr
                    tput el
                    local pad=$(( (width - plen - ilen) / 2 + offset ))
                    (( pad < 0 )) && pad=0
                    printf "%*s%s%s" "$pad" "" "$prompt" "$input"
                else
                    echo -n "$char"
                fi
            fi
        done
        echo ""
        if [[ -n "$readvar" ]]; then
            printf -v "$readvar" '%s' "$input"
        fi
        stty "$stty"
    fi
}

wait_enter() {
    read_center "Press Enter to continue..."
}

disable_input() {
    stty -echo
    tput civis
}

enable_input() {
    stty echo
    tput cnorm
}

hang() {
    disable_input
	sleep infinity || reboot -f
}

fail() {
    export errormsg="$1"
	sync
    cd /
    umount /dev/loop*p* 2>/dev/null
    umount /dev/loop* 2>/dev/null
    for arg in "$@"; do
        if [ "$arg" = "--fatal" ]; then
            echo_c "A fatal error occured. Please Reboot" RED_B | center
            hang
        fi
    done
    return 1
}

term_login() {
    clear
    cat /etc/motd
    echo
    for attempt in 1 2 3; do
        stty intr '' erase '^H'
        read -p "$(hostname) login: " username
        if id "$username" >/dev/null 2>&1; then
            return 0
        else
            echo "Invalid User"
        fi
    done
    export username="root"
}

echo_menu() {
    local text="$1"
    while IFS= read -r line; do
        local length=${#line}
        local spacing=$(( (42 - length) / 2 ))
        spacing=$((spacing < 0 ? 0 : spacing))
        printf "%*s%s\n" "$spacing" "" "$line"
    done <<< "$text"
}

menu() {
    local prompt="$1"
    shift
    local args=""
    if [[ "$1" == "-p" ]]; then
        args="$1"
        shift
    fi
    local options=("$@")
    local selected=0
    local count=${#options[@]}
    updatedpage=0
    tput civis
    echo "$prompt" | center
    for i in "${!options[@]}"; do
        if [[ $i -eq $selected ]]; then
            echo "> ${options[i]} <" | center
        else
            echo "${options[i]}" | center
        fi
    done
    while true; do
        tput cuu $count
        for i in "${!options[@]}"; do
            tput el
            if [[ $i -eq $selected ]]; then
                echo "> ${options[i]} <" | center
            else
                echo "${options[i]}" | center
            fi
        done

        IFS= read -rsn1 key
        if [[ $key == $'\e' ]]; then
            read -rsn2 -t 0.01 key_rest
            key+="$key_rest"
        fi
        if [ "$args" = "-p" ]; then
            case $key in
                $'\e[A') ((selected--)) ;;
                $'\e[B') ((selected++)) ;;
				$'\e[D') export page=$((page - 1)) updatedpage=1 && return 255 ;;
				$'\e[C') export page=$((page + 1)) updatedpage=1 && return 255 ;;
                '') break ;;
            esac
        else
            case $key in
                $'\e[A') ((selected--)) ;;
                $'\e[B') ((selected++)) ;;
                '') break ;;
            esac
        fi
        ((selected < 0)) && selected=$((count - 1))
        ((selected >= count)) && selected=0
    done
    return $selected
}

splash() {
    if [ "$(lsbval shrimp /etc/aurora)" == "1" ]; then
        shrimp
        printf "\033[H"
        clear
    fi
    if cat /sys/devices/virtual/dmi/id/product_name 2>$TTY4 | grep -Eqi 'treeya|barla' 2>$TTY4; then
        echo -e "${RED_B}Barla/Treeya wifi unsupported. Please contact @kxtzownsu on discord${COLOR_RESET}"
    else
        signal=$(iw dev $wifidevice link | grep signal | awk '{print $2}' | sed 's/.00//' | head -1)
        if (( signal >= -50 )); then color=$'\e[1;38;5;82m'; strength=$'▃▅▇'
        elif (( signal >= -60 )); then color=$'\e[1;38;5;226m'; strength=$'▃▅\e[1;38;5;236m▇'
        elif (( signal >= -70 )); then color=$'\e[1;38;5;208m'; strength=$'▃\e[1;38;5;236m▅▇'
        else color=$'\e[1;38;5;196m'; strength=$'▃\e[1;38;5;236m▅▇'; fi
        ssid="$(iw dev "$wifidevice" link 2>$TTY4 | awk -F ': ' '/SSID/ {print $2}')"
        if [ -f /etc/aftggp ]; then
            ssid="$ssid | ${CYAN_B}AFT running at: $(ip a | grep $wifidevice | grep inet | awk '{print $2}' | sed 's|/.*||'):42069${COLOR_RESET}"
        fi
        if [ -n "$ssid" ]; then
            echo -e "\n${color}${strength}${color} $wifidevice${COLOR_RESET} $ssid" | center
        else
            echo -e "\n\e[1;38;5;196m▃\e[1;38;5;236m▅▇\e[1;38;5;196m $wifidevice${COLOR_RESET} disconnected" | center
        fi
    fi
    local width=42
	local verstring=${VERSION["STRING"]}
	local build=${VERSION["BUILDDATE"]}
	local version_pad=$(( (width - ${#verstring}) / 2 ))
    local build_pad=$(( (width - ${#build}) / 2 ))
    echo -ne "$CYAN_B"
    cat <<'EOF' | center
╒════════════════════════════════════════╕
│ .    . .    '    +   *       o    .    │
│+  '.                    '   .-.     +  │
│          +      .    +   .   ) )     ''│
│                   '  .      '-´  *.    │
│     .    \      .     .  .  +          │
│         .-o-'       '    .o        o   │
│  *        \      *            +'       │
│                '       '               │
│        .*       .       o   o      .   │
│              o     . *.                │
│ 'o*           .        .'    .         │
│              ┏┓   '. O           *     │
│     .*       ┣┫┓┏┏┓┏┓┏┓┏┓  .    \      │
│     o        ┛┗┗┛┛ ┗┛┛ ┗┻     +        │
╘════════════════════════════════════════╛
EOF
    echo -ne "$CYAN_B"
    echo -e "\n$verstring" | center
    echo -e "$build" | center
    kernelver=$(getkv)
    if [ -f /etc/kernverpending ]; then
        kernelver=$(cat /etc/kernverpending)
        echo -e "$kernelver ${YELLOW_B}(pending reboot)${COLOR_RESET}" | center
    else
        echo -e "$kernelver" | center
    fi
    echo -e "\nhttps://github.com/AerialiteLabs/Aurora" | center
	echo -e "Page ${page}${COLOR_RESET}" | center
    funText | center
}

lsbval() {
  local key="$1"
  local lsbfile="${2:-/etc/lsb-release}"

  if ! echo "${key}" | grep -Eq '^[a-zA-Z0-9_]+$'; then
    return 1
  fi

  sed -E -n -e \
    "/^[[:space:]]*${key}[[:space:]]*=/{
      s:^[^=]+=[[:space:]]*::
      s:[[:space:]]+$::
      p
    }" "${lsbfile}"
}

versions() {
    echo ""
    local release_board=$(lsbval CHROMEOS_RELEASE_BOARD 2>$TTY4)
    export board_name=${release_board%%-*}
    echo "What ChromeOS version do you want to download?" | center
	options_install=(
	    "Latest Version"
	    "Custom Version"
	)

	menu "Select an option (use ↑ ↓ arrows, Enter to select)" "${options_install[@]}"
	install_choice=$?

	case "$install_choice" in
	    0) chromeVersion="latest" ;;
	    1) stty echo
           read_center -d "Enter Version: " chromeVersion ;;
        *) fail "Invalid choice (somehow?????)" ;;
	esac
    echo "Fetching recovery image..." | center
    if [ $chromeVersion == "latest" ]; then
        builds="https://chromiumdash.appspot.com/cros/fetch_serving_builds?deviceCategory=Chrome%20OS"
        chromeVersion=$(curl -s $builds | jq -r ".builds.${board_name}.models | to_entries[0].value.servingStable.chromeVersion" | awk -F. '{print $1}')
        FINAL_URL=$(curl -s $builds | jq -r ".builds.${board_name}.models | to_entries[0].value.pushRecoveries[\"$chromeVersion\"]")
        if [ ! -n $FINAL_URL ]; then
            echo "Falling back to the most recent version found." | center
            FINAL_URL=$(curl -s $builds | jq ".builds.${board_name}.models | to_entries[0].value.pushRecoveries | to_entries | sort_by(.key | tonumber) | .[-1].value")
        fi
        [ -n "$chromeVersion" ] || fail "Failed finding Version"
        export chromeVersion
        export FINAL_URL
    else
        export url="https://raw.githubusercontent.com/MercuryWorkshop/chromeos-releases-data/refs/heads/main/data.json"
        cros_json=$(curl -s "$url" | jq --arg board "$board_name" --arg ver "$chromeVersion" '.[$board].images[] | select((.chrome_version | tostring) | test("^" + $ver))')
        if [[ -z "$cros_json" ]]; then return; fi
        cros_platform=$(echo "$cros_json" | jq -r '.platform_version'| head -1 )
        cros_url=$(echo "$cros_json" | jq -r '.url' | head -1 )
        last_modified=$(echo "$cros_json" | jq -r '.last_modified' | head -1 )
        MATCH_FOUND=0
        if [[ -n "$cros_url" ]]; then
            echo "Found a $chromeVersion match on platform $cros_platform from $last_modified." | center
            MATCH_FOUND=1
            export FINAL_URL="$cros_url"
            return 0
        fi
        if [ $MATCH_FOUND -eq 0 ]; then
            echo "No recovery image found for your board and target version. Exiting" | center
            return 1
        fi
    fi
}

export_args() {
    local arg=
    local key=
    local val=
    local acceptable_set='[A-Za-z0-9]_'
    echo "Exporting kernel argument..."
    for arg in "$@"; do
        key=$(echo "${arg%%=*}" | busybox tr 'a-z' 'A-Z' | busybox tr -dc "$acceptable_set" '_')
        val="${arg#*=}"
        export "KERN_ARG_$key"="$val"
        echo -n " KERN_ARG_$key=$val,"
    done
    echo ""
}

is_good_rootfs_partition() {
    local root_dev="$1"
    local sector_count
    sector_count="$(cat "/sys/class/block/$(basename "${root_dev}")/size")"
    local sector_count_threshold=1
    [ "${sector_count}" -gt "${sector_count_threshold}" ]
}

strip_partition() {
    local dev="${1%p[0-9]*}"
    echo "$dev"
}

wait_for_gpt_root() {
    [ -z "$KERN_ARG_KERN_GUID" ] && return 1
    local try kern_dev kern_num
    local root_dev root_num
    for try in $(seq 20); do
        kern_dev="$(cgpt find -l KERN-A ${USB_DEV})" || kern_dev="${USB_DEV}p2"
        kern_num=${kern_dev##[/a-z]*[/a-z]}
        for offset in 1 -1; do
        root_num=$(( kern_num + ${offset} ))
        root_dev="${kern_dev%${kern_num}}${root_num}"
        if [ -b "${root_dev}" ] && is_good_rootfs_partition "${root_dev}"; then
            USB_DEV="${root_dev}"
            return 0
        fi
        done
        sleep 1
    done
    return 1
}

mount_rootfs() {
    local usb_dev
    local kernel_command_line="$(cat /proc/cmdline)"
    usb_dev="${USB_DEV}"
    for try in $(seq 20); do
        if mount -n -o ro "$usb_dev" "$USB_MNT"; then
        return 0
        fi
        sleep 1
    done
    return 1
}

patch_new_root() {
  local bootstrap="${NEWROOT_MNT}/usr/sbin/factory_bootstrap.sh"
  local flag="/tmp/bootstrap.failed"
  if [ -x "${bootstrap}" ]; then
    rm -f "${flag}"
    "${bootstrap}" "${NEWROOT_MNT}" "${REAL_USB_DEV}"
    if [ -e "${flag}" ]; then
      return 1
    fi
  fi
}

find_official_root() {
    set -x
    wait_for_gpt_root
    cgpt find -t rootfs "$(strip_partition "$USB_DEV")" || fail "An error has occured."
    REAL_USB_DEV="$USB_DEV"
    LOG_DEV="${USB_DEV%p[0-9]*}p1"
    mount_rootfs
}

copy_lsb() {
    echo "Copying lsb..."

    local lsb_file="dev_image/etc/lsb-factory"
    local dest_path="/newroot/mnt/stateful_partition/${lsb_file}"
    local src_path="/stateful/${lsb_file}"
    
    mkdir -p "$(dirname "${dest_path}")"
    
    local ret=0
    if [ -f "${src_path}" ]; then
        local kern_guid=$(echo "${KERN_ARG_KERN_GUID}" | tr '[:lower:]' '[:upper:]')
        echo "Found ${src_path}"
        cp -a "${src_path}" "${dest_path}"
        echo "REAL_USB_DEV=${loop}p3" >>"${dest_path}"
        echo "KERN_ARG_KERN_GUID=${kern_guid}" >>"${dest_path}"
    else
        echo "Failed to find ${src_path}!!"
        ret=1
    fi
    return "${ret}"
}

pv_dircopy() {
	[ -d "$1" ] || return 1
	local apparent_bytes
	apparent_bytes=$(du -sb "$1" | cut -f 1)
	mkdir -p "$2"
	tar -cf - -C "$1" . | pv -f -s "${apparent_bytes:-0}" | tar -xf - -C "$2"
}

setupuser() {
    read_center -d "Username: " username
    stty -echo
    read_center -d "Password: " password
    stty echo 
    adduser -D "$username"
    echo "$username:$password" | chpasswd 2>$TTY4
    echo "$username ALL=(ALL:ALL) ALL" >> /etc/sudoers
    mkdir -p /run/user/$(id -u $username)
    chown $username:$username /run/user/$(id -u $username)
    addgroup $username video
    addgroup $username seat 2>/dev/null
}

setup() {
    tput cnorm
    stty echo
    if [ "$(lsbval setup /etc/aurora)" == "1" ]; then
        clear
        splash
        echo -e "\nSetup Aurora" | center
        read_center -d "Setup a user? (Y/n) " setupuser
        case $setupuser in
            n|N) ;;
            *) setupuser ;;
        esac
        while true; do
            read_center -d "Enter your timezone: " timezone
            timezone="*$(echo "$timezone" | sed 's/ /*/g')*"
            timezonefile=$(find /usr/share/zoneinfo -type f -iname "$timezone" | head -1)
            if [[ -z "$timezonefile" ]]; then echo "Invalid timezone" | center; continue; fi
            rm -rf /etc/localtime
            ln -s "$timezonefile" /etc/localtime
            break
        done
        read_center -d "Change Hostname? (y/N): " changehostname
        case $changehostname in
            y) read_center -d "Hostname: " hostname
               hostname $hostname
               echo "$hostname" > /etc/hostname
               echo "127.0.0.1 localhost $hostname" >> /etc/hosts ;;
            *) hostname Aurora
               echo "Aurora" > /etc/hostname
               echo "127.0.0.1 localhost Aurora" >> /etc/hosts ;;
        esac
        sed -i 's/setup=1/setup=0/' /etc/aurora
    fi
    tput civis
    stty -echo
}

spinner() {
    local pid=$1
    local delay=0.2
    local spinstr='|/-\'
    
    # Capture start time
    local start_time=$SECONDS
    
    # Hide cursor
    tput civis 

    while kill -0 "$pid" 2>/dev/null; do
        local temp=${spinstr#?}
        printf "\e[0;36m [%c] " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b" # Clears the "[x] "
    done

    # Calculate total time
    local total_seconds=$(( SECONDS - start_time ))
    
    # Convert to minutes and seconds
    local m=$(( total_seconds / 60 ))
    local s=$(( total_seconds % 60 ))

    # Restore cursor
    tput cnorm

    # Logic to print either "1m 10s" or just "10s"
    if [ $m -gt 0 ]; then
        echo -e "\e[1;32mDone in ${m}m ${s}s!\e[0m \n"
    else
        echo -e "\e[1;32mDone in ${s}s!\e[0m \n"
    fi
}

install_pkgs() {
  echo -e "\e[1;36mUpdating packages..."
  sudo apk update >/dev/null 2>&1 && sudo apk upgrade >/dev/null 2>&1 &
  spinner $!

  echo -e "\e[1;36mInstalling needed packages and deps..."
  {

    sudo apk add e2fsprogs e2fsprogs-extra >/dev/null
    sudo apk add coreutils man-db partx sgdisk file rsync cgpt curl wget gptfdisk util-linux bash libfdisk >/dev/null
    sudo apk add protoc gzip py3-pip zlib cryptsetup >/dev/null
    sudo apk add make cmake neovim vim >/dev/null

  } &

  spinner $!

  echo -e "\e[1;36mInstalling python and pip..."
  sudo apk add python3 python3-dev py3-setuptools py-distutils-extra >/dev/null &

  spinner $!

  echo -e "\e[1;36mInstalling lvm tools"
  sudo apk add lvm2 lvm2-extra lvm2-lockd lvm2-libs >/dev/null &

  spinner $!

  echo -e "\e[1;36mInstalling pip packages..."

  {

    python3 -m venv install >/dev/null
    source install/bin/activate >/dev/null
    pip3 install pipx >/dev/null
    pip3 install Pillow >/dev/null
    pip3 install image-tools >/dev/null
    pip3 install protobuf >/dev/null
    pip3 install six >/devnull
    pip install --upgrade pip >/dev/null
  
  } &

  spinner $!

}

dl_reco_image() {
  read -p "Enter your board name: " board
  echo -e "\e[1;32mInstalling ${board} v139 recovery image]"
  if [ $board == nissa ]; then
    wget -P /usr/share/aurora/images/recovery/ https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_16328.65.0_nissa_recovery_stable-channel_NissaMPKeys-v58.bin.zip -O v139.bin
    spinner $!
  elif [ $board == octopus ]; then
    wget -p /usr/share/aurora/images/recovery/ https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_16328.65.0_octopus_recovery_stable-channel_OctopusMPKeys-v37.bin.zip -O v139.bin
  fi
}


