#!/bin/bash
# Sets up aurora with needed packages and dependencies
# TODO: Make code cleaner, add color, add auto shim download
echo "Updating packages"
sudo apk update && sudo apk upgrade >/dev/null
echo "Installing needed packages and deps"
sudo apk add e2fsprogs e2fsprogs-extra >/dev/null
sudo apk add coreutils man-db partx sgdisk file rsync cgpt curl wget gptfdisk util-linux bash zsh libfdisk >/dev/null
sudo apk add protoc gzip py3-pip zlib cryptsetup >/dev/null
sudo apk add make cmake neovim vim >/dev/null
echo "Installing python and pip"
sudo apk add python3 python3-dev py3-setuptools py-distutils-extra >/dev/null
echo "Installing lvm tools"
sudo apk add lvm2 lvm2-extra lvm2-lockd lvm2-libs >/dev/null
echo "Installing pip packages"
python3 -m venv install >/dev/null
source install/bin/activate >/dev/null
pip3 install pipx >/dev/null
pip3 install Pillow >/dev/null
pip3 install image-tools >/dev/null
pip3 install protobuf >/dev/null
pip3 install six >/devnull
pip install --upgrade pip >/dev/null
clear
